/*
 * Galacticraft Capes API
 * Galacticraft Cape API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GalacticraftCapesApi);
  }
}(this, function(expect, GalacticraftCapesApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Player', function() {
      beforeEach(function() {
        instance = new GalacticraftCapesApi.Player();
      });

      it('should create an instance of Player', function() {
        // TODO: update the code to test Player
        expect(instance).to.be.a(GalacticraftCapesApi.Player);
      });

      it('should have the property uuid (base name: "uuid")', function() {
        // TODO: update the code to test the property uuid
        expect(instance).to.have.property('uuid');
        // expect(instance.uuid).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property cape (base name: "cape")', function() {
        // TODO: update the code to test the property cape
        expect(instance).to.have.property('cape');
        // expect(instance.cape).to.be(expectedValueLiteral);
      });

      it('should have the property allowedCapes (base name: "allowedCapes")', function() {
        // TODO: update the code to test the property allowedCapes
        expect(instance).to.have.property('allowedCapes');
        // expect(instance.allowedCapes).to.be(expectedValueLiteral);
      });

    });
  });

}));
